const mockCampeonatos = [
  {
    campeonato_id: 10,
    nome: "Campeonato Brasileiro",
    slug: "campeonato-brasileiro",
    nome_popular: "Brasileirão",
    edicao_atual: {
      edicao_id: 36,
      temporada: "2022",
      nome: "Campeonato Brasileiro 2022",
      nome_popular: "Brasileirão 2022",
      slug: "campeonato-brasileiro-2022",
    },
    fase_atual: {
      fase_id: 168,
      nome: "Fase Única",
      slug: "fase-unica",
      tipo: "pontos-corridos",
      _link: "/v1/campeonatos/10/fases/168",
    },
    rodada_atual: {
      nome: "38ª Rodada",
      slug: "38a-rodada",
      rodada: 38,
      status: "encerrada",
    },
    status: "finalizado",
    tipo: "Pontos Corridos",
    logo: "https://api.api-futebol.com.br/images/competicao/brasileiro-seriea.png",
    _link: "/v1/campeonatos/10",
  },
  {
    campeonato_id: 2,
    nome: "Copa do Brasil",
    slug: "copa-do-brasil",
    nome_popular: "Copa do Brasil",
    edicao_atual: {
      edicao_id: 38,
      temporada: "2022",
      nome: "Copa do Brasil 2022",
      nome_popular: "Copa do Brasil 2022",
      slug: "copa-do-brasil-2022",
    },
    fase_atual: {
      fase_id: 176,
      nome: "Final",
      slug: "final",
      tipo: "mata-mata",
      _link: "/v1/campeonatos/2/fases/176",
    },
    rodada_atual: null,
    status: "finalizado",
    tipo: "Mata-Mata",
    logo: "https://api.api-futebol.com.br/images/competicao/copa-do-brasil.png",
    _link: "/v1/campeonatos/2",
  },
  {
    campeonato_id: 22,
    nome: "Campeonato Baiano",
    slug: "campeonato-baiano",
    nome_popular: "Baianão",
    edicao_atual: {
      edicao_id: 49,
      temporada: "2023",
      nome: "Campeonato Baiano 2023",
      nome_popular: "Baianão 2023",
      slug: "campeonato-baiano-2023",
    },
    fase_atual: {
      fase_id: 227,
      nome: "Primeira Fase",
      slug: "primeira-fase",
      tipo: "grupos",
      _link: "/v1/campeonatos/22/fases/227",
    },
    rodada_atual: null,
    status: "agendado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/campeonato-baiano.png",
    _link: "/v1/campeonatos/22",
  },
  {
    campeonato_id: 14,
    nome: "Campeonato Brasileiro Série B",
    slug: "campeonato-brasileiro-serie-b",
    nome_popular: "Brasileirão Série B",
    edicao_atual: {
      edicao_id: 37,
      temporada: "2022",
      nome: "Campeonato Brasileiro Série B 2022",
      nome_popular: "Brasileirão Série B 2022",
      slug: "campeonato-brasileiro-serie-b-2022",
    },
    fase_atual: {
      fase_id: 169,
      nome: "Fase Única",
      slug: "fase-unica",
      tipo: "pontos-corridos",
      _link: "/v1/campeonatos/14/fases/169",
    },
    rodada_atual: {
      nome: "38ª Rodada",
      slug: "38a-rodada",
      rodada: 38,
      status: "encerrada",
    },
    status: "finalizado",
    tipo: "Pontos Corridos",
    logo: "https://api.api-futebol.com.br/images/competicao/brasileiro-serieb.png",
    _link: "/v1/campeonatos/14",
  },
  {
    campeonato_id: 16,
    nome: "Campeonato Brasileiro Série C",
    slug: "campeonato-brasileiro-serie-c",
    nome_popular: "Brasileirão Série C",
    edicao_atual: {
      edicao_id: 41,
      temporada: "2022",
      nome: "Campeonato Brasileiro Série C 2022",
      nome_popular: "Brasileirão Série C 2022",
      slug: "campeonato-brasileiro-serie-c-2022",
    },
    fase_atual: {
      fase_id: 193,
      nome: "Final",
      slug: "final",
      tipo: "mata-mata",
      _link: "/v1/campeonatos/16/fases/193",
    },
    rodada_atual: null,
    status: "finalizado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/brasileiro-seriec.png",
    _link: "/v1/campeonatos/16",
  },
  {
    campeonato_id: 17,
    nome: "Campeonato Brasileiro Série D",
    slug: "campeonato-brasileiro-serie-d",
    nome_popular: "Brasileirão Série D",
    edicao_atual: {
      edicao_id: 42,
      temporada: "2022",
      nome: "Campeonato Brasileiro Série D 2022",
      nome_popular: "Brasileirão Série D 2022",
      slug: "campeonato-brasileiro-serie-d-2022",
    },
    fase_atual: {
      fase_id: 199,
      nome: "Final",
      slug: "final",
      tipo: "mata-mata",
      _link: "/v1/campeonatos/17/fases/199",
    },
    rodada_atual: null,
    status: "finalizado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/brasileiro-seried.png",
    _link: "/v1/campeonatos/17",
  },
  {
    campeonato_id: 6,
    nome: "Campeonato Carioca",
    slug: "campeonato-carioca",
    nome_popular: "Carioca",
    edicao_atual: {
      edicao_id: 46,
      temporada: "2023",
      nome: "Campeonato Carioca 2023",
      nome_popular: "Carioca 2023",
      slug: "campeonato-carioca-2023",
    },
    fase_atual: {
      fase_id: 218,
      nome: "Taça Guanabara",
      slug: "taca-guanabara",
      tipo: "grupos",
      _link: "/v1/campeonatos/6/fases/218",
    },
    rodada_atual: null,
    status: "agendado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/carioca.png",
    _link: "/v1/campeonatos/6",
  },
  {
    campeonato_id: 13,
    nome: "Campeonato Catarinense",
    slug: "campeonato-catarinense",
    nome_popular: "Catarinense",
    edicao_atual: {
      edicao_id: 50,
      temporada: "2023",
      nome: "Campeonato Catarinense 2023",
      nome_popular: "Catarinense 2023",
      slug: "campeonato-catarinense-2023",
    },
    fase_atual: {
      fase_id: 230,
      nome: "Primeira Fase",
      slug: "primeira-fase",
      tipo: "grupos",
      _link: "/v1/campeonatos/13/fases/230",
    },
    rodada_atual: null,
    status: "agendado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/campeonato-catarinense.png",
    _link: "/v1/campeonatos/13",
  },
  {
    campeonato_id: 23,
    nome: "Campeonato Cearense",
    slug: "campeonato-cearense",
    nome_popular: "Cearense",
    edicao_atual: {
      edicao_id: 51,
      temporada: "2023",
      nome: "Campeonato Cearense 2023",
      nome_popular: "Cearense 2023",
      slug: "campeonato-cearense-2023",
    },
    fase_atual: {
      fase_id: 234,
      nome: "Primeira Fase",
      slug: "primeira-fase",
      tipo: "grupo-contra-grupo",
      _link: "/v1/campeonatos/23/fases/234",
    },
    rodada_atual: {
      nome: "1ª Rodada",
      slug: "1a-rodada",
      rodada: 1,
      status: "agendada",
    },
    status: "andamento",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/campeonato-cearense.png",
    _link: "/v1/campeonatos/23",
  },
  {
    campeonato_id: 11,
    nome: "Campeonato Gaúcho",
    slug: "campeonato-gaucho",
    nome_popular: "Gaúcho",
    edicao_atual: {
      edicao_id: 52,
      temporada: "2023",
      nome: "Campeonato Gaúcho 2023",
      nome_popular: "Gaúcho 2023",
      slug: "campeonato-gaucho-2023",
    },
    fase_atual: {
      fase_id: 238,
      nome: "Primeira Fase",
      slug: "primeira-fase",
      tipo: "grupos",
      _link: "/v1/campeonatos/11/fases/238",
    },
    rodada_atual: null,
    status: "agendado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/campeonato-gaucho.png",
    _link: "/v1/campeonatos/11",
  },
  {
    campeonato_id: 21,
    nome: "Campeonato Goiano",
    slug: "campeonato-goiano",
    nome_popular: "Goianão",
    edicao_atual: {
      edicao_id: 53,
      temporada: "2023",
      nome: "Campeonato Goiano 2023",
      nome_popular: "Goianão 2023",
      slug: "campeonato-goiano-2023",
    },
    fase_atual: {
      fase_id: 241,
      nome: "Primeira Fase",
      slug: "primeira-fase",
      tipo: "grupos",
      _link: "/v1/campeonatos/21/fases/241",
    },
    rodada_atual: null,
    status: "agendado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/campeonato-goiano.jpeg",
    _link: "/v1/campeonatos/21",
  },
  {
    campeonato_id: 12,
    nome: "Campeonato Mineiro",
    slug: "campeonato-mineiro",
    nome_popular: "Mineiro",
    edicao_atual: {
      edicao_id: 45,
      temporada: "2023",
      nome: "Campeonato Mineiro 2023",
      nome_popular: "Mineiro 2023",
      slug: "campeonato-mineiro-2023",
    },
    fase_atual: {
      fase_id: 212,
      nome: "Primeira Fase",
      slug: "primeira-fase",
      tipo: "grupo-contra-grupo",
      _link: "/v1/campeonatos/12/fases/212",
    },
    rodada_atual: {
      nome: "1ª Rodada",
      slug: "1a-rodada",
      rodada: 1,
      status: "agendada",
    },
    status: "agendado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/campeonato-mineiro.png",
    _link: "/v1/campeonatos/12",
  },
  {
    campeonato_id: 9,
    nome: "Campeonato Paulista",
    slug: "campeonato-paulista",
    nome_popular: "Paulista",
    edicao_atual: {
      edicao_id: 47,
      temporada: "2023",
      nome: "Campeonato Paulista 2023",
      nome_popular: "Paulista 2023",
      slug: "campeonato-paulista-2023",
    },
    fase_atual: {
      fase_id: 223,
      nome: "Primeira Fase",
      slug: "primeira-fase",
      tipo: "grupo-contra-grupo",
      _link: "/v1/campeonatos/9/fases/223",
    },
    rodada_atual: {
      nome: "1ª Rodada",
      slug: "1a-rodada",
      rodada: 1,
      status: "agendada",
    },
    status: "agendado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/campeonato-paulista.png",
    _link: "/v1/campeonatos/9",
  },
  {
    campeonato_id: 25,
    nome: "Campeonato Pernambucano",
    slug: "campeonato-pernambucano",
    nome_popular: "Pernambucano",
    edicao_atual: {
      edicao_id: 55,
      temporada: "2023",
      nome: "Campeonato Pernambucano 2023",
      nome_popular: "Pernambucano 2023",
      slug: "pernambucano-2023",
    },
    fase_atual: {
      fase_id: 249,
      nome: "Primeira Fase",
      slug: "primeira-fase",
      tipo: "grupos",
      _link: "/v1/campeonatos/25/fases/249",
    },
    rodada_atual: null,
    status: "agendado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/campeonato-pernambucano.png",
    _link: "/v1/campeonatos/25",
  },
  {
    campeonato_id: 20,
    nome: "Champions League",
    slug: "champions-league",
    nome_popular: "Champions League",
    edicao_atual: {
      edicao_id: 44,
      temporada: "2022-2023",
      nome: "Champions League 2022-2023",
      nome_popular: "Champions League 2022-2023",
      slug: "champions-league-22-23",
    },
    fase_atual: {
      fase_id: 208,
      nome: "Oitavas de Final",
      slug: "oitavas-de-final",
      tipo: "mata-mata",
      _link: "/v1/campeonatos/20/fases/208",
    },
    rodada_atual: null,
    status: "andamento",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/championsleague.png",
    _link: "/v1/campeonatos/20",
  },
  {
    campeonato_id: 18,
    nome: "Copa América",
    slug: "copa-america",
    nome_popular: "Copa América",
    edicao_atual: {
      edicao_id: 24,
      temporada: "2021",
      nome: "Copa América 2021",
      nome_popular: "Copa América 2021",
      slug: "copa-america-2021",
    },
    fase_atual: {
      fase_id: 120,
      nome: "Final",
      slug: "final",
      tipo: "mata-mata",
      _link: "/v1/campeonatos/18/fases/120",
    },
    rodada_atual: null,
    status: "finalizado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/copa-america.png",
    _link: "/v1/campeonatos/18",
  },
  {
    campeonato_id: 24,
    nome: "Copa do Mundo",
    slug: "copa-do-mundo",
    nome_popular: "Copa do Mundo",
    edicao_atual: {
      edicao_id: 43,
      temporada: "Catar 2022",
      nome: "Copa do Mundo Catar 2022",
      nome_popular: "Copa do Mundo Catar 2022",
      slug: "copa-do-mundo-catar-2022",
    },
    fase_atual: {
      fase_id: 205,
      nome: "Final",
      slug: "final",
      tipo: "mata-mata",
      _link: "/v1/campeonatos/24/fases/205",
    },
    rodada_atual: null,
    status: "finalizado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/copa-do-mundo-2022.png",
    _link: "/v1/campeonatos/24",
  },
  {
    campeonato_id: 15,
    nome: "Copa do Nordeste",
    slug: "copa-do-nordeste",
    nome_popular: "Copa do Nordeste",
    edicao_atual: {
      edicao_id: 54,
      temporada: "2023",
      nome: "Copa do Nordeste 2023",
      nome_popular: "Copa do Nordeste 2023",
      slug: "copa-do-nordeste-2023",
    },
    fase_atual: {
      fase_id: 245,
      nome: "Fase de Grupos",
      slug: "fase-de-grupos",
      tipo: "grupo-contra-grupo",
      _link: "/v1/campeonatos/15/fases/245",
    },
    rodada_atual: {
      nome: "1ª Rodada",
      slug: "1a-rodada",
      rodada: 1,
      status: "agendada",
    },
    status: "agendado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/copa-do-nordeste.png",
    _link: "/v1/campeonatos/15",
  },
  {
    campeonato_id: 7,
    nome: "Copa Libertadores da América",
    slug: "copa-libertadores-da-america",
    nome_popular: "Libertadores",
    edicao_atual: {
      edicao_id: 39,
      temporada: "2022",
      nome: "Copa Libertadores da América 2022",
      nome_popular: "Libertadores 2022",
      slug: "copa-libertadores-da-america-2022",
    },
    fase_atual: {
      fase_id: 184,
      nome: "Final",
      slug: "final",
      tipo: "mata-mata",
      _link: "/v1/campeonatos/7/fases/184",
    },
    rodada_atual: null,
    status: "finalizado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/libertadores.png",
    _link: "/v1/campeonatos/7",
  },
  {
    campeonato_id: 8,
    nome: "Copa Sulamericana",
    slug: "copa-sulamericana",
    nome_popular: "Sulamericana",
    edicao_atual: {
      edicao_id: 40,
      temporada: "2022",
      nome: "Copa Sulamericana 2022",
      nome_popular: "Sulamericana 2022",
      slug: "copa-sul-americana-2022",
    },
    fase_atual: {
      fase_id: 190,
      nome: "Final",
      slug: "final",
      tipo: "mata-mata",
      _link: "/v1/campeonatos/8/fases/190",
    },
    rodada_atual: null,
    status: "finalizado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/sulamericana.png",
    _link: "/v1/campeonatos/8",
  },
  {
    campeonato_id: 19,
    nome: "Eurocopa",
    slug: "eurocopa",
    nome_popular: "Eurocopa",
    edicao_atual: {
      edicao_id: 25,
      temporada: "2020",
      nome: "Eurocopa 2020",
      nome_popular: "Eurocopa 2020",
      slug: "eurocopa-2020",
    },
    fase_atual: {
      fase_id: 125,
      nome: "Final",
      slug: "final",
      tipo: "mata-mata",
      _link: "/v1/campeonatos/19/fases/125",
    },
    rodada_atual: null,
    status: "finalizado",
    tipo: "Misto",
    logo: "https://api.api-futebol.com.br/images/competicao/eurocopa.png",
    _link: "/v1/campeonatos/19",
  },
];

const mockRodadas = [
  {
    nome: "1ª Rodada",
    slug: "1a-rodada",
    rodada: 1,
    status: "encerrada",
    proxima_rodada: {
      nome: "2ª Rodada",
      slug: "2a-rodada",
      rodada: 2,
      status: "encerrada",
    },
    rodada_anterior: null,
    _link: "/v1/campeonatos/10/rodadas/1",
  },
  {
    nome: "2ª Rodada",
    slug: "2a-rodada",
    rodada: 2,
    status: "encerrada",
    proxima_rodada: {
      nome: "3ª Rodada",
      slug: "3a-rodada",
      rodada: 3,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "1ª Rodada",
      slug: "1a-rodada",
      rodada: 1,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/2",
  },
  {
    nome: "3ª Rodada",
    slug: "3a-rodada",
    rodada: 3,
    status: "encerrada",
    proxima_rodada: {
      nome: "4ª Rodada",
      slug: "4a-rodada",
      rodada: 4,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "2ª Rodada",
      slug: "2a-rodada",
      rodada: 2,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/3",
  },
  {
    nome: "4ª Rodada",
    slug: "4a-rodada",
    rodada: 4,
    status: "encerrada",
    proxima_rodada: {
      nome: "5ª Rodada",
      slug: "5a-rodada",
      rodada: 5,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "3ª Rodada",
      slug: "3a-rodada",
      rodada: 3,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/4",
  },
  {
    nome: "5ª Rodada",
    slug: "5a-rodada",
    rodada: 5,
    status: "encerrada",
    proxima_rodada: {
      nome: "6ª Rodada",
      slug: "6a-rodada",
      rodada: 6,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "4ª Rodada",
      slug: "4a-rodada",
      rodada: 4,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/5",
  },
  {
    nome: "6ª Rodada",
    slug: "6a-rodada",
    rodada: 6,
    status: "encerrada",
    proxima_rodada: {
      nome: "7ª Rodada",
      slug: "7a-rodada",
      rodada: 7,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "5ª Rodada",
      slug: "5a-rodada",
      rodada: 5,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/6",
  },
  {
    nome: "7ª Rodada",
    slug: "7a-rodada",
    rodada: 7,
    status: "encerrada",
    proxima_rodada: {
      nome: "8ª Rodada",
      slug: "8a-rodada",
      rodada: 8,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "6ª Rodada",
      slug: "6a-rodada",
      rodada: 6,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/7",
  },
  {
    nome: "8ª Rodada",
    slug: "8a-rodada",
    rodada: 8,
    status: "encerrada",
    proxima_rodada: {
      nome: "9ª Rodada",
      slug: "9a-rodada",
      rodada: 9,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "7ª Rodada",
      slug: "7a-rodada",
      rodada: 7,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/8",
  },
  {
    nome: "9ª Rodada",
    slug: "9a-rodada",
    rodada: 9,
    status: "encerrada",
    proxima_rodada: {
      nome: "10ª Rodada",
      slug: "10a-rodada",
      rodada: 10,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "8ª Rodada",
      slug: "8a-rodada",
      rodada: 8,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/9",
  },
  {
    nome: "10ª Rodada",
    slug: "10a-rodada",
    rodada: 10,
    status: "encerrada",
    proxima_rodada: {
      nome: "11ª Rodada",
      slug: "11a-rodada",
      rodada: 11,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "9ª Rodada",
      slug: "9a-rodada",
      rodada: 9,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/10",
  },
  {
    nome: "11ª Rodada",
    slug: "11a-rodada",
    rodada: 11,
    status: "encerrada",
    proxima_rodada: {
      nome: "12ª Rodada",
      slug: "12a-rodada",
      rodada: 12,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "10ª Rodada",
      slug: "10a-rodada",
      rodada: 10,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/11",
  },
  {
    nome: "12ª Rodada",
    slug: "12a-rodada",
    rodada: 12,
    status: "encerrada",
    proxima_rodada: {
      nome: "13ª Rodada",
      slug: "13a-rodada",
      rodada: 13,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "11ª Rodada",
      slug: "11a-rodada",
      rodada: 11,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/12",
  },
  {
    nome: "13ª Rodada",
    slug: "13a-rodada",
    rodada: 13,
    status: "encerrada",
    proxima_rodada: {
      nome: "14ª Rodada",
      slug: "14a-rodada",
      rodada: 14,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "12ª Rodada",
      slug: "12a-rodada",
      rodada: 12,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/13",
  },
  {
    nome: "14ª Rodada",
    slug: "14a-rodada",
    rodada: 14,
    status: "encerrada",
    proxima_rodada: {
      nome: "15ª Rodada",
      slug: "15a-rodada",
      rodada: 15,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "13ª Rodada",
      slug: "13a-rodada",
      rodada: 13,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/14",
  },
  {
    nome: "15ª Rodada",
    slug: "15a-rodada",
    rodada: 15,
    status: "encerrada",
    proxima_rodada: {
      nome: "16ª Rodada",
      slug: "16a-rodada",
      rodada: 16,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "14ª Rodada",
      slug: "14a-rodada",
      rodada: 14,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/15",
  },
  {
    nome: "16ª Rodada",
    slug: "16a-rodada",
    rodada: 16,
    status: "encerrada",
    proxima_rodada: {
      nome: "17ª Rodada",
      slug: "17a-rodada",
      rodada: 17,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "15ª Rodada",
      slug: "15a-rodada",
      rodada: 15,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/16",
  },
  {
    nome: "17ª Rodada",
    slug: "17a-rodada",
    rodada: 17,
    status: "encerrada",
    proxima_rodada: {
      nome: "18ª Rodada",
      slug: "18a-rodada",
      rodada: 18,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "16ª Rodada",
      slug: "16a-rodada",
      rodada: 16,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/17",
  },
  {
    nome: "18ª Rodada",
    slug: "18a-rodada",
    rodada: 18,
    status: "encerrada",
    proxima_rodada: {
      nome: "19ª Rodada",
      slug: "19a-rodada",
      rodada: 19,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "17ª Rodada",
      slug: "17a-rodada",
      rodada: 17,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/18",
  },
  {
    nome: "19ª Rodada",
    slug: "19a-rodada",
    rodada: 19,
    status: "encerrada",
    proxima_rodada: {
      nome: "20ª Rodada",
      slug: "20a-rodada",
      rodada: 20,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "18ª Rodada",
      slug: "18a-rodada",
      rodada: 18,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/19",
  },
  {
    nome: "20ª Rodada",
    slug: "20a-rodada",
    rodada: 20,
    status: "encerrada",
    proxima_rodada: {
      nome: "21ª Rodada",
      slug: "21a-rodada",
      rodada: 21,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "19ª Rodada",
      slug: "19a-rodada",
      rodada: 19,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/20",
  },
  {
    nome: "21ª Rodada",
    slug: "21a-rodada",
    rodada: 21,
    status: "encerrada",
    proxima_rodada: {
      nome: "22ª Rodada",
      slug: "22a-rodada",
      rodada: 22,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "20ª Rodada",
      slug: "20a-rodada",
      rodada: 20,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/21",
  },
  {
    nome: "22ª Rodada",
    slug: "22a-rodada",
    rodada: 22,
    status: "encerrada",
    proxima_rodada: {
      nome: "23ª Rodada",
      slug: "23a-rodada",
      rodada: 23,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "21ª Rodada",
      slug: "21a-rodada",
      rodada: 21,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/22",
  },
  {
    nome: "23ª Rodada",
    slug: "23a-rodada",
    rodada: 23,
    status: "encerrada",
    proxima_rodada: {
      nome: "24ª Rodada",
      slug: "24a-rodada",
      rodada: 24,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "22ª Rodada",
      slug: "22a-rodada",
      rodada: 22,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/23",
  },
  {
    nome: "24ª Rodada",
    slug: "24a-rodada",
    rodada: 24,
    status: "encerrada",
    proxima_rodada: {
      nome: "25ª Rodada",
      slug: "25a-rodada",
      rodada: 25,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "23ª Rodada",
      slug: "23a-rodada",
      rodada: 23,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/24",
  },
  {
    nome: "25ª Rodada",
    slug: "25a-rodada",
    rodada: 25,
    status: "encerrada",
    proxima_rodada: {
      nome: "26ª Rodada",
      slug: "26a-rodada",
      rodada: 26,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "24ª Rodada",
      slug: "24a-rodada",
      rodada: 24,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/25",
  },
  {
    nome: "26ª Rodada",
    slug: "26a-rodada",
    rodada: 26,
    status: "encerrada",
    proxima_rodada: {
      nome: "27ª Rodada",
      slug: "27a-rodada",
      rodada: 27,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "25ª Rodada",
      slug: "25a-rodada",
      rodada: 25,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/26",
  },
  {
    nome: "27ª Rodada",
    slug: "27a-rodada",
    rodada: 27,
    status: "encerrada",
    proxima_rodada: {
      nome: "28ª Rodada",
      slug: "28a-rodada",
      rodada: 28,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "26ª Rodada",
      slug: "26a-rodada",
      rodada: 26,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/27",
  },
  {
    nome: "28ª Rodada",
    slug: "28a-rodada",
    rodada: 28,
    status: "encerrada",
    proxima_rodada: {
      nome: "29ª Rodada",
      slug: "29a-rodada",
      rodada: 29,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "27ª Rodada",
      slug: "27a-rodada",
      rodada: 27,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/28",
  },
  {
    nome: "29ª Rodada",
    slug: "29a-rodada",
    rodada: 29,
    status: "encerrada",
    proxima_rodada: {
      nome: "30ª Rodada",
      slug: "30a-rodada",
      rodada: 30,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "28ª Rodada",
      slug: "28a-rodada",
      rodada: 28,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/29",
  },
  {
    nome: "30ª Rodada",
    slug: "30a-rodada",
    rodada: 30,
    status: "encerrada",
    proxima_rodada: {
      nome: "31ª Rodada",
      slug: "31a-rodada",
      rodada: 31,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "29ª Rodada",
      slug: "29a-rodada",
      rodada: 29,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/30",
  },
  {
    nome: "31ª Rodada",
    slug: "31a-rodada",
    rodada: 31,
    status: "encerrada",
    proxima_rodada: {
      nome: "32ª Rodada",
      slug: "32a-rodada",
      rodada: 32,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "30ª Rodada",
      slug: "30a-rodada",
      rodada: 30,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/31",
  },
  {
    nome: "32ª Rodada",
    slug: "32a-rodada",
    rodada: 32,
    status: "encerrada",
    proxima_rodada: {
      nome: "33ª Rodada",
      slug: "33a-rodada",
      rodada: 33,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "31ª Rodada",
      slug: "31a-rodada",
      rodada: 31,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/32",
  },
  {
    nome: "33ª Rodada",
    slug: "33a-rodada",
    rodada: 33,
    status: "encerrada",
    proxima_rodada: {
      nome: "34ª Rodada",
      slug: "34a-rodada",
      rodada: 34,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "32ª Rodada",
      slug: "32a-rodada",
      rodada: 32,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/33",
  },
  {
    nome: "34ª Rodada",
    slug: "34a-rodada",
    rodada: 34,
    status: "encerrada",
    proxima_rodada: {
      nome: "35ª Rodada",
      slug: "35a-rodada",
      rodada: 35,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "33ª Rodada",
      slug: "33a-rodada",
      rodada: 33,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/34",
  },
  {
    nome: "35ª Rodada",
    slug: "35a-rodada",
    rodada: 35,
    status: "encerrada",
    proxima_rodada: {
      nome: "36ª Rodada",
      slug: "36a-rodada",
      rodada: 36,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "34ª Rodada",
      slug: "34a-rodada",
      rodada: 34,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/35",
  },
  {
    nome: "36ª Rodada",
    slug: "36a-rodada",
    rodada: 36,
    status: "encerrada",
    proxima_rodada: {
      nome: "37ª Rodada",
      slug: "37a-rodada",
      rodada: 37,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "35ª Rodada",
      slug: "35a-rodada",
      rodada: 35,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/36",
  },
  {
    nome: "37ª Rodada",
    slug: "37a-rodada",
    rodada: 37,
    status: "encerrada",
    proxima_rodada: {
      nome: "38ª Rodada",
      slug: "38a-rodada",
      rodada: 38,
      status: "encerrada",
    },
    rodada_anterior: {
      nome: "36ª Rodada",
      slug: "36a-rodada",
      rodada: 36,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/37",
  },
  {
    nome: "38ª Rodada",
    slug: "38a-rodada",
    rodada: 38,
    status: "encerrada",
    proxima_rodada: null,
    rodada_anterior: {
      nome: "37ª Rodada",
      slug: "37a-rodada",
      rodada: 37,
      status: "encerrada",
    },
    _link: "/v1/campeonatos/10/rodadas/38",
  },
];

const mockCampeonato = {
  campeonato_id: 10,
  nome: "Campeonato Brasileiro",
  slug: "campeonato-brasileiro",
  nome_popular: "Brasileirão",
  edicao_atual: {
    edicao_id: 36,
    temporada: "2022",
    nome: "Campeonato Brasileiro 2022",
    nome_popular: "Brasileirão 2022",
    slug: "campeonato-brasileiro-2022",
  },
  fase_atual: {
    fase_id: 168,
    nome: "Fase Única",
    slug: "fase-unica",
    tipo: "pontos-corridos",
    _link: "/v1/campeonatos/10/fases/168",
  },
  rodada_atual: {
    nome: "38ª Rodada",
    slug: "38a-rodada",
    rodada: 38,
    status: "encerrada",
  },
  status: "finalizado",
  tipo: "Pontos Corridos",
  logo: "https://api.api-futebol.com.br/images/competicao/brasileiro-seriea.png",
  regiao: "nacional",
  fases: [
    {
      fase_id: 168,
      edicao: {
        edicao_id: 36,
        temporada: "2022",
        nome: "Campeonato Brasileiro 2022",
        nome_popular: "Brasileirão 2022",
        slug: "campeonato-brasileiro-2022",
      },
      nome: "Fase Única",
      slug: "fase-unica",
      status: "finalizado",
      decisivo: false,
      eliminatorio: false,
      ida_e_volta: true,
      tipo: "pontos-corridos",
      grupos: [],
      chaves: [],
      rodadas: [],
      proxima_fase: null,
      fase_anterior: null,
      _link: "/v1/campeonatos/10/fases/168",
    },
  ],
};

const mockRodada1 = {
  nome: "1ª Rodada",
  slug: "1a-rodada",
  rodada: 1,
  status: "encerrada",
  proxima_rodada: {
    nome: "2ª Rodada",
    slug: "2a-rodada",
    rodada: 2,
    status: "encerrada",
  },
  rodada_anterior: null,
  partidas: [
    {
      partida_id: 4844,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Fluminense 0x0 Santos",
      time_mandante: {
        time_id: 26,
        nome_popular: "Fluminense",
        sigla: "FLU",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3492a6e0b.svg",
      },
      time_visitante: {
        time_id: 63,
        nome_popular: "Santos",
        sigla: "SAN",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a5749d6.svg",
      },
      placar_mandante: 0,
      placar_visitante: 0,
      disputa_penalti: false,
      status: "finalizado",
      slug: "fluminense-santos-4844",
      data_realizacao: "09/04/2022",
      hora_realizacao: "16:30",
      data_realizacao_iso: "2022-04-09T16:30:00-0300",
      estadio: {
        estadio_id: 19,
        nome_popular: "Maracanã",
      },
      _link: "/v1/partidas/4844",
    },
    {
      partida_id: 4850,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Atlético-GO 1x1 Flamengo",
      time_mandante: {
        time_id: 98,
        nome_popular: "Atlético-GO",
        sigla: "ACG",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34b9174a3.svg",
      },
      time_visitante: {
        time_id: 18,
        nome_popular: "Flamengo",
        sigla: "FLA",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d348e3f815.svg",
      },
      placar_mandante: 1,
      placar_visitante: 1,
      disputa_penalti: false,
      status: "finalizado",
      slug: "atletico-go-flamengo-4850",
      data_realizacao: "09/04/2022",
      hora_realizacao: "19:00",
      data_realizacao_iso: "2022-04-09T19:00:00-0300",
      estadio: {
        estadio_id: 337,
        nome_popular: "Antônio Accioly",
      },
      _link: "/v1/partidas/4850",
    },
    {
      partida_id: 4846,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Palmeiras 2x3 Ceará",
      time_mandante: {
        time_id: 56,
        nome_popular: "Palmeiras",
        sigla: "PAL",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a1cf247.svg",
      },
      time_visitante: {
        time_id: 105,
        nome_popular: "Ceará",
        sigla: "CEA",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34bcb81bc.svg",
      },
      placar_mandante: 2,
      placar_visitante: 3,
      disputa_penalti: false,
      status: "finalizado",
      slug: "palmeiras-ceara-4846",
      data_realizacao: "09/04/2022",
      hora_realizacao: "21:00",
      data_realizacao_iso: "2022-04-09T21:00:00-0300",
      estadio: {
        estadio_id: 327,
        nome_popular: "Allianz Parque",
      },
      _link: "/v1/partidas/4846",
    },
    {
      partida_id: 4852,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Coritiba 3x0 Goiás",
      time_mandante: {
        time_id: 84,
        nome_popular: "Coritiba",
        sigla: "CFC",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34b1296c2.svg",
      },
      time_visitante: {
        time_id: 115,
        nome_popular: "Goiás",
        sigla: "GOI",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34c1c1d9f.svg",
      },
      placar_mandante: 3,
      placar_visitante: 0,
      disputa_penalti: false,
      status: "finalizado",
      slug: "coritiba-goias-4852",
      data_realizacao: "10/04/2022",
      hora_realizacao: "11:00",
      data_realizacao_iso: "2022-04-10T11:00:00-0300",
      estadio: {
        estadio_id: 317,
        nome_popular: "Couto Pereira",
      },
      _link: "/v1/partidas/4852",
    },
    {
      partida_id: 4843,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Atlético-MG 2x0 Internacional",
      time_mandante: {
        time_id: 30,
        nome_popular: "Atlético-MG",
        sigla: "CAM",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3494f3380.svg",
      },
      time_visitante: {
        time_id: 44,
        nome_popular: "Internacional",
        sigla: "INT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349b92103.svg",
      },
      placar_mandante: 2,
      placar_visitante: 0,
      disputa_penalti: false,
      status: "finalizado",
      slug: "atletico-mg-internacional-4843",
      data_realizacao: "10/04/2022",
      hora_realizacao: "16:00",
      data_realizacao_iso: "2022-04-10T16:00:00-0300",
      estadio: {
        estadio_id: 42,
        nome_popular: "Mineirão",
      },
      _link: "/v1/partidas/4843",
    },
    {
      partida_id: 4847,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Botafogo 1x3 Corinthians",
      time_mandante: {
        time_id: 22,
        nome_popular: "Botafogo",
        sigla: "BOT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349052558.svg",
      },
      time_visitante: {
        time_id: 65,
        nome_popular: "Corinthians",
        sigla: "COR",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a68419f.svg",
      },
      placar_mandante: 1,
      placar_visitante: 3,
      disputa_penalti: false,
      status: "finalizado",
      slug: "botafogo-corinthians-4847",
      data_realizacao: "10/04/2022",
      hora_realizacao: "16:00",
      data_realizacao_iso: "2022-04-10T16:00:00-0300",
      estadio: {
        estadio_id: 26,
        nome_popular: "Nilton Santos (Engenhão)",
      },
      _link: "/v1/partidas/4847",
    },
    {
      partida_id: 4849,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Fortaleza 0x1 Cuiabá",
      time_mandante: {
        time_id: 131,
        nome_popular: "Fortaleza",
        sigla: "FOR",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34c76d067.svg",
      },
      time_visitante: {
        time_id: 204,
        nome_popular: "Cuiabá",
        sigla: "CUI",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34ebcdafa.svg",
      },
      placar_mandante: 0,
      placar_visitante: 1,
      disputa_penalti: false,
      status: "finalizado",
      slug: "fortaleza-cuiaba-4849",
      data_realizacao: "10/04/2022",
      hora_realizacao: "18:00",
      data_realizacao_iso: "2022-04-10T18:00:00-0300",
      estadio: {
        estadio_id: 112,
        nome_popular: "Castelão (CE)",
      },
      _link: "/v1/partidas/4849",
    },
    {
      partida_id: 4845,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "São Paulo 4x0 Athletico-PR",
      time_mandante: {
        time_id: 57,
        nome_popular: "São Paulo",
        sigla: "SAO",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a23c311.svg",
      },
      time_visitante: {
        time_id: 185,
        nome_popular: "Athletico-PR",
        sigla: "CAP",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34e1b8948.svg",
      },
      placar_mandante: 4,
      placar_visitante: 0,
      disputa_penalti: false,
      status: "finalizado",
      slug: "sao-paulo-athletico-pr-4845",
      data_realizacao: "10/04/2022",
      hora_realizacao: "19:00",
      data_realizacao_iso: "2022-04-10T19:00:00-0300",
      estadio: {
        estadio_id: 63,
        nome_popular: "Morumbi",
      },
      _link: "/v1/partidas/4845",
    },
    {
      partida_id: 4851,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Avaí 1x0 América-MG",
      time_mandante: {
        time_id: 6,
        nome_popular: "Avaí",
        sigla: "AVA",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3487aa471.svg",
      },
      time_visitante: {
        time_id: 33,
        nome_popular: "América-MG",
        sigla: "AMG",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34966e9c6.svg",
      },
      placar_mandante: 1,
      placar_visitante: 0,
      disputa_penalti: false,
      status: "finalizado",
      slug: "avai-america-mg-4851",
      data_realizacao: "10/04/2022",
      hora_realizacao: "19:00",
      data_realizacao_iso: "2022-04-10T19:00:00-0300",
      estadio: {
        estadio_id: 10,
        nome_popular: "Ressacada",
      },
      _link: "/v1/partidas/4851",
    },
    {
      partida_id: 4848,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Juventude 2x2 Bragantino",
      time_mandante: {
        time_id: 43,
        nome_popular: "Juventude",
        sigla: "JUV",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349b308c6.svg",
      },
      time_visitante: {
        time_id: 64,
        nome_popular: "Bragantino",
        sigla: "BGT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a5db2ec.svg",
      },
      placar_mandante: 2,
      placar_visitante: 2,
      disputa_penalti: false,
      status: "finalizado",
      slug: "juventude-bragantino-4848",
      data_realizacao: "11/04/2022",
      hora_realizacao: "20:00",
      data_realizacao_iso: "2022-04-11T20:00:00-0300",
      estadio: {
        estadio_id: 50,
        nome_popular: "Alfredo Jaconi",
      },
      _link: "/v1/partidas/4848",
    },
  ],
  _link: "/v1/campeonatos/10/rodadas/1",
};

const mockRodada2 = {
  nome: "2ª Rodada",
  slug: "2a-rodada",
  rodada: 2,
  status: "encerrada",
  proxima_rodada: {
    nome: "3ª Rodada",
    slug: "3a-rodada",
    rodada: 3,
    status: "encerrada",
  },
  rodada_anterior: {
    nome: "1ª Rodada",
    slug: "1a-rodada",
    rodada: 1,
    status: "encerrada",
  },
  partidas: [
    {
      partida_id: 4860,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Goiás 1x1 Palmeiras",
      time_mandante: {
        time_id: 115,
        nome_popular: "Goiás",
        sigla: "GOI",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34c1c1d9f.svg",
      },
      time_visitante: {
        time_id: 56,
        nome_popular: "Palmeiras",
        sigla: "PAL",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a1cf247.svg",
      },
      placar_mandante: 1,
      placar_visitante: 1,
      disputa_penalti: false,
      status: "finalizado",
      slug: "goias-palmeiras-4860",
      data_realizacao: "16/04/2022",
      hora_realizacao: "16:30",
      data_realizacao_iso: "2022-04-16T16:30:00-0300",
      estadio: {
        estadio_id: 543,
        nome_popular: "Hailé Pinheiro (Serrinha)",
      },
      _link: "/v1/partidas/4860",
    },
    {
      partida_id: 4853,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "América-MG 4x1 Juventude",
      time_mandante: {
        time_id: 33,
        nome_popular: "América-MG",
        sigla: "AMG",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34966e9c6.svg",
      },
      time_visitante: {
        time_id: 43,
        nome_popular: "Juventude",
        sigla: "JUV",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349b308c6.svg",
      },
      placar_mandante: 4,
      placar_visitante: 1,
      disputa_penalti: false,
      status: "finalizado",
      slug: "america-mg-juventude-4853",
      data_realizacao: "16/04/2022",
      hora_realizacao: "19:00",
      data_realizacao_iso: "2022-04-16T19:00:00-0300",
      estadio: {
        estadio_id: 27,
        nome_popular: "Independência",
      },
      _link: "/v1/partidas/4853",
    },
    {
      partida_id: 4856,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Corinthians 3x0 Avaí",
      time_mandante: {
        time_id: 65,
        nome_popular: "Corinthians",
        sigla: "COR",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a68419f.svg",
      },
      time_visitante: {
        time_id: 6,
        nome_popular: "Avaí",
        sigla: "AVA",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3487aa471.svg",
      },
      placar_mandante: 3,
      placar_visitante: 0,
      disputa_penalti: false,
      status: "finalizado",
      slug: "corinthians-avai-4856",
      data_realizacao: "16/04/2022",
      hora_realizacao: "19:00",
      data_realizacao_iso: "2022-04-16T19:00:00-0300",
      estadio: {
        estadio_id: 329,
        nome_popular: "Neo Química Arena",
      },
      _link: "/v1/partidas/4856",
    },
    {
      partida_id: 4861,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Cuiabá 0x1 Fluminense",
      time_mandante: {
        time_id: 204,
        nome_popular: "Cuiabá",
        sigla: "CUI",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34ebcdafa.svg",
      },
      time_visitante: {
        time_id: 26,
        nome_popular: "Fluminense",
        sigla: "FLU",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3492a6e0b.svg",
      },
      placar_mandante: 0,
      placar_visitante: 1,
      disputa_penalti: false,
      status: "finalizado",
      slug: "cuiaba-fluminense-4861",
      data_realizacao: "16/04/2022",
      hora_realizacao: "21:00",
      data_realizacao_iso: "2022-04-16T21:00:00-0300",
      estadio: {
        estadio_id: 95,
        nome_popular: "Arena Pantanal",
      },
      _link: "/v1/partidas/4861",
    },
    {
      partida_id: 4857,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Santos 2x1 Coritiba",
      time_mandante: {
        time_id: 63,
        nome_popular: "Santos",
        sigla: "SAN",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a5749d6.svg",
      },
      time_visitante: {
        time_id: 84,
        nome_popular: "Coritiba",
        sigla: "CFC",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34b1296c2.svg",
      },
      placar_mandante: 2,
      placar_visitante: 1,
      disputa_penalti: false,
      status: "finalizado",
      slug: "santos-coritiba-4857",
      data_realizacao: "17/04/2022",
      hora_realizacao: "11:00",
      data_realizacao_iso: "2022-04-17T11:00:00-0300",
      estadio: {
        estadio_id: 66,
        nome_popular: "Vila Belmiro",
      },
      _link: "/v1/partidas/4857",
    },
    {
      partida_id: 4854,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Flamengo 3x1 São Paulo",
      time_mandante: {
        time_id: 18,
        nome_popular: "Flamengo",
        sigla: "FLA",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d348e3f815.svg",
      },
      time_visitante: {
        time_id: 57,
        nome_popular: "São Paulo",
        sigla: "SAO",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a23c311.svg",
      },
      placar_mandante: 3,
      placar_visitante: 1,
      disputa_penalti: false,
      status: "finalizado",
      slug: "flamengo-sao-paulo-4854",
      data_realizacao: "17/04/2022",
      hora_realizacao: "16:00",
      data_realizacao_iso: "2022-04-17T16:00:00-0300",
      estadio: {
        estadio_id: 19,
        nome_popular: "Maracanã",
      },
      _link: "/v1/partidas/4854",
    },
    {
      partida_id: 4855,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Bragantino 4x0 Atlético-GO",
      time_mandante: {
        time_id: 64,
        nome_popular: "Bragantino",
        sigla: "BGT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34a5db2ec.svg",
      },
      time_visitante: {
        time_id: 98,
        nome_popular: "Atlético-GO",
        sigla: "ACG",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34b9174a3.svg",
      },
      placar_mandante: 4,
      placar_visitante: 0,
      disputa_penalti: false,
      status: "finalizado",
      slug: "bragantino-atletico-go-4855",
      data_realizacao: "17/04/2022",
      hora_realizacao: "18:00",
      data_realizacao_iso: "2022-04-17T18:00:00-0300",
      estadio: {
        estadio_id: 73,
        nome_popular: "Nabi Abi Chedid",
      },
      _link: "/v1/partidas/4855",
    },
    {
      partida_id: 4858,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Internacional 2x1 Fortaleza",
      time_mandante: {
        time_id: 44,
        nome_popular: "Internacional",
        sigla: "INT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349b92103.svg",
      },
      time_visitante: {
        time_id: 131,
        nome_popular: "Fortaleza",
        sigla: "FOR",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34c76d067.svg",
      },
      placar_mandante: 2,
      placar_visitante: 1,
      disputa_penalti: false,
      status: "finalizado",
      slug: "internacional-fortaleza-4858",
      data_realizacao: "17/04/2022",
      hora_realizacao: "18:00",
      data_realizacao_iso: "2022-04-17T18:00:00-0300",
      estadio: {
        estadio_id: 53,
        nome_popular: "Beira-Rio",
      },
      _link: "/v1/partidas/4858",
    },
    {
      partida_id: 4862,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Athletico-PR 0x1 Atlético-MG",
      time_mandante: {
        time_id: 185,
        nome_popular: "Athletico-PR",
        sigla: "CAP",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34e1b8948.svg",
      },
      time_visitante: {
        time_id: 30,
        nome_popular: "Atlético-MG",
        sigla: "CAM",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d3494f3380.svg",
      },
      placar_mandante: 0,
      placar_visitante: 1,
      disputa_penalti: false,
      status: "finalizado",
      slug: "athletico-pr-atletico-mg-4862",
      data_realizacao: "17/04/2022",
      hora_realizacao: "18:00",
      data_realizacao_iso: "2022-04-17T18:00:00-0300",
      estadio: {
        estadio_id: 291,
        nome_popular: "Arena da Baixada",
      },
      _link: "/v1/partidas/4862",
    },
    {
      partida_id: 4859,
      campeonato: {
        campeonato_id: 10,
        nome: "Campeonato Brasileiro",
        slug: "campeonato-brasileiro",
      },
      placar: "Ceará 1x3 Botafogo",
      time_mandante: {
        time_id: 105,
        nome_popular: "Ceará",
        sigla: "CEA",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d34bcb81bc.svg",
      },
      time_visitante: {
        time_id: 22,
        nome_popular: "Botafogo",
        sigla: "BOT",
        escudo: "https://cdn.api-futebol.com.br/escudos/638d349052558.svg",
      },
      placar_mandante: 1,
      placar_visitante: 3,
      disputa_penalti: false,
      status: "finalizado",
      slug: "ceara-botafogo-4859",
      data_realizacao: "17/04/2022",
      hora_realizacao: "19:00",
      data_realizacao_iso: "2022-04-17T19:00:00-0300",
      estadio: {
        estadio_id: 112,
        nome_popular: "Castelão (CE)",
      },
      _link: "/v1/partidas/4859",
    },
  ],
  _link: "/v1/campeonatos/10/rodadas/2",
};

export {
  mockCampeonatos,
  mockRodadas,
  mockCampeonato,
  mockRodada1,
  mockRodada2,
};
